### PR TITLE
CODE RUB: AppSettings JWT Configure Core.Api

### PR DESCRIPTION
**Pull request by glhays**
@SlimAhmad
1> Your attempt to to use the StaticConfig in the startup does not work in static classes, I noticed a similar suggested use in a post online but it was not complete. You need to find a more elegant way to implement your retrieval of settings from appsettings. What I did will allow you to at least complete the testing.

2> Your project is at most 40% Standard Compliant (JMO)

3> The two tests pass now, I also upgraded a couple to the new Standard version v2.10.0
Note: I highly encourage you to go through the contribution links learn about The Standard, The Standard Team - these docs will help you tremendously
Using the old repositories from the HassanHabib library is a start, but alot of the standard coding is outdated and or has been upgraded.
Take some time now and while your codebase is manageable to refactor it.

4> Have any questions reach out.

I see you have followed Luke some. Fasseto was a nice series.

### CODE REVIEW

**Comment by SlimAhmad** [comment]
@glhays Thank you, I really appreciate your review.

1. I saw a blog post on injecting my app settings model through dependency injection [https://www.c-sharpcorner.com/article/reading-values-from-appsettings-json-in-asp-net-core/](url), I'll be making those changes today.
2. It means a lot getting a 40% review, wasn't expecting to get that much. 
3. I just found out about processing services and orchestration services; I think my Auth-service is a processing service cause I'm making use of multiple foundation services in it. I'll read more about it and implement. still trying to wrap my head around orchestration though. 

Yeah, I did follow Luke a bit his was series with Fasseto-word was very good, The framework constructions and stuff. was wondering though if it's standard compliant going that route.

**Comment by glhays** [comment]
> @glhays Thank you, I really appreciate your review.
> 
> 1. I saw a blog post on injecting my app settings model through dependency injection [https://www.c-sharpcorner.com/article/reading-values-from-appsettings-json-in-asp-net-core/](url), I'll be making those changes today.
> 2. It means a lot getting a 40% review, wasn't expecting to get that much.
> 3. I just found out about processing services and orchestration services; I think my Auth-service is a processing service cause I'm making use of multiple foundation services in it. I'll read more about it and implement. still trying to wrap my head around orchestration though.
> 
> Yeah, I did follow Luke a bit his was series with Fasseto-word was very good, The framework constructions and stuff. was wondering though if it's standard compliant going that route.

I will checkout that link.
Yes I did notice that you were handling multiple routines in your foundation services, which in turn your testing structure as well does not comply to the standard. Once you have a grip on processing services, orchestrations follow in a similar pattern.
The Luke code I remember is not Standard Compliant.
Watch The Standard YouTube series https://youtube.com/playlist?list=PLan3SCnsISTQqmSTZHQbGxBmVDwQdrlub&si=k_wyJ7NslT86gbWt
Many of videos are based on Taarofo.core https://youtube.com/playlist?list=PLan3SCnsISTQNkgtVMqJu896TghXjGYzt&si=96LHl4BZrxea_wuj
I have an open pr on Taarofo upgrading it to The Standard version 2.10.0 if you want to check it out on upgrading your tests.

**Comment by SlimAhmad** [comment]
@glhays ,so I've been reading about processing  and orchestration. Was wondering of userManager from identity falls under utilities  like logging broker for me to make use of in my processing services. 

Thanks for the resources, I started going through them last night and I'll be going through the  PR with taarafoo

**Comment by glhays** [comment]
@SlimAhmad 
I encourage you to read the Brokers section of The Standard carefully and thoroughly. It states in paragraph 1 of the introduction the following. 

"Brokers are a liaison between business logic and the outside world. They are wrappers around external libraries, resources, services, or APIs to satisfy a local interface for the business to interact with them without having to be tightly coupled with any particular resources or external library implementation."

Please note you will be tightly coupled to AspNet.Identity, you have no control over it whatsoever in using it in your application, or can you switch it out with another authentication framework.
Point in fact. Your current test ConfirmEmail returns an error, not so much as the email is not confirmed but the user object between your application user model does not coincide with the authuser from aspnet identity. To the best of my recollection you can add fields to identity but not remove the default entity members and why would you. So tightly coupled in MOP. I guess I have a question will you be using the default identity tables in your db?

**Comment by SlimAhmad** [comment]
@glhays  I noticed it to ,  been working on a work around for that  to pass on the random identity  user to my object values  during the test. The plan was initially to make use of the the identity table's   but I'm open for any suggestions or guides in the right path to follow authorisation and authentication according to the standard

**Comment by glhays** [comment]
> @glhays  I noticed it to ,  been working on a work around for that  to pass on the random identity  user to my object values  during the test. The plan was initially to make use of the the identity table's   but I'm open for any suggestions or guides in the right path.
> 

I sent a friend request in discord, will be easier to discuss these different approaches.

**Comment by SlimAhmad** [comment]
@glhays Thank you .

**Pull request merged**
